In [ ]:
#a.Импортируйте библиотеку NumPy
import numpy as np

In [ ]:
#b.Создайте массив из 10 нулей
import numpy as np
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#c.Создать массив из 10 единиц
import numpy as np
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#d.Создать массив из 10 пятерок
import numpy as np
print(np.ones(10) * 5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#e.Создать массив из целых чисел от 10 до 50
import numpy as np
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#f.Создать массив из четных чисел от 10 до 50
import numpy as np
print(np.arange(10,50,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
#g.Создать матрицу 3х3 с числами от 0 до 8
import numpy as np
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#h.Создать единичную матрицу 3x3
import numpy as np
print(np.ones(9).reshape(3,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#i.Используйте NumPy для генерации случайного числа от 0 до 1
import numpy as np
print(np.random.randint(0,2))

0


In [ ]:
#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
import numpy as np
print(np.random.randn(25))

[-0.38027915 -0.58828161 -0.80394081 -0.68107032  1.11817667 -0.19908951
 -1.03079801 -0.99529417 -0.31660865 -1.80564275 -1.22628856 -0.26692279
 -1.2601432  -0.44943816  0.72254527 -0.19216514 -0.63787724 -0.74844635
 -0.24053403 -0.31830774 -0.41175952  1.26641474 -1.23951287  0.79604228
 -0.36158808]


In [ ]:
#k.Создайте следующую матрицу используя функции библиотеки NumPy
import numpy as np
print(np.arange(0.01, 1.01, 0.01).reshape(10, 10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
#l.Необходимо написать код который вернет следующую матрицуиз стартовой
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat[2:, 1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
#m.Написать код обращения к элементу который вернет значение  20 из стартовой матрицы задачи l.
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat[3, 4])

20


In [ ]:
#n.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat[0:3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
#o.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat[-1])

[21 22 23 24 25]


In [ ]:
#p.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat[-2:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#q.Получить сумму всех значений в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat.sum())

325


In [ ]:
#r.Получить стандартное отклонение в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


In [ ]:
#s.Получить сумму значений в колонках в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat.sum(axis =0))

[55 60 65 70 75]
